query GetProductByName(
    $productName: String!
  ) {
    getProductByName(productName: $productName) {
      _id
      userId
      ibmDiscoveryDocumentId
      status
      archived
      name
      description
      values {
        name
        description
      }
      features {
        label
        value
      }
      plans {
        name
        price
        description
      }
      featured {
        url
      }
    }
  }