query ProductByName(
    $productName: String!
  ) {
    productByName(productName: $productName) {
      _id
      userId
      ibmDiscoveryDocumentId
      status
      archived
      name
      summary
      description
      values {
        name
        description
      }
      features {
        label
        value
      }
      plans {
        name
        price
        features {
          _id
          label
          value
        }
      }
      featured {
        url
      }
    }
  }