query SearchProducts(
    $query: String!
  ) {
    searchProducts(
      searchQueryInput: {
        query: $query
      }
    ) {
      name
      description
      featured {
        url
      }
    }
  }
